### PR TITLE
admin 1.1

### PR DESCRIPTION
**Pull request by JarekW**

### CODE REVIEW

**Comment by szymach** [comment]
zrób jeszcze wersję 1.0.0 dla admina 1.0

**Comment by JarekW** [comment]
maybe there should be another branch for admin 1.1 ?

**Comment by szymach** [comment]
Perhaps, though I doubt we'll be doing any updates to the 1.0 branch.

**Comment by JarekW** [comment]
@fsi-open there is a branch `1.0`, tag `v1.0.0` points to it and pull is for master (`1.1-dev`)

**Comment by rn0** [comment]
:+1:

**Comment by szymach** [comment]
:+1:

**Comment by JarekW** [comment]
@chives

**Comment by chives** [comment]
@JarekW would you add php 5.6 to travis build matrix?

**Comment by JarekW** [comment]
@chives added

**Comment by chives** [comment]
:+1:

**Pull request merged**
